- .pre-commit-config.yaml
* adding gitleaks precommit config to all repos
> adding gitleaks precommit config

- scripts/aws-mfa-session.sh
[PLT-84](https://jira.cms.gov/browse/PLT-84)
Script added for setting up MFA session for AWS access on the command line.
> PLT-84 Add script for mfa session

- scripts/encryption_auditor.py
https://jira.cms.gov/browse/PLT-55
at rest encryption checker base script
For a quick list of all unencrypted S3 buckets, EC2 volumes, and RDS instances in our accounts.
Shared output looks correct.
> add at rest encryption auditor script

- terraform/services/github-actions/deploy-roles/main.tf
> fix tag:Session issue

- .github/workflows/github-actions-terraform-plan.yml
- .github/workflows/terraform-fmt.yml
https://jira.cms.gov/browse/PLT-193
Added a workflow for github-actions terraform that calls the reusable terraform-fmt workflow.
This is a minimal proof for testing out reusable workflows, and allows for exploring some ideas to expand in #13.
Testing workflows before the PR is merged is tricky. We'll likely need to test after merge, then create a follow-up PR if there are issues.
> PLT-193 Workflow for github-actions calling reusable workflow

- .github/workflows/github-actions-terraform-plan.yml
- .github/workflows/terraform-fmt.yml
- actions/setup-tfenv-terraform/action.yml
https://jira.cms.gov/browse/PLT-193
Adjusting the workflow for terraform plan on github-actions to allow it to run.
With merge of #16 we have the github-actions-terraform-plan workflow in main, and now I can see errors to fix.
See checks in this PR for successful run of the workflow.
> PLT-193 Fix for github-actions terraform plan workflow

- .github/workflows/github-actions-terraform-apply.yml
https://jira.cms.gov/browse/PLT-193
Added workflow file for github-actions terraform apply.
Adding the initial workflow file in this PR so we can test following merge to main, then I'll iterate on fixes in #13.
I'll check the actions log and iterate once this is merged.
> PLT-193 Add initial apply workflow for github-actions terraform

- terraform/services/github-actions/main.tf
https://jira.cms.gov/browse/PLT-216
Added idle config to actions runners 
> PLT-216: Set idle config on Github Actions Runners

- .github/workflows/opt-out-inbound-apply.yml
- .github/workflows/opt-out-inbound-plan.yml
https://jira.cms.gov/browse/PLT-176
Workflows added to handle terraform plan and apply for opt-out-inbound.
These are just the initial drafts of the workflows. I'll iterate on them with the terraform in #11.
I'll test in #11 once they're merged.
> PLT-176 Add apply and plan workflows for opt-out-inbound

- .github/workflows/opt-out-import-apply.yml
- .github/workflows/opt-out-import-plan.yml
https://jira.cms.gov/browse/PLT-176
Change references from opt-out-inbound to opt-out-import.
Standardizing the two sides of the opt-out process on import and export.
This will need to be merged before we can test the workflow, and checks will fail for now because they depend on code in #11.
None.
> PLT-176 Switch opt-out-inbound workflow from inbound to import

- terraform/services/github-actions-deploy-role/main.tf
https://jira.cms.gov/browse/PLT-285
Added instance profile for the deploy role.
Workflow runs for #37 are failing because there is no instance profile for the deploy role.
We'll need to test in #37 following apply.
None.
> PLT-285 Add instance profile resource in deploy role terraform

- .github/workflows/opt-out-import-apply.yml
https://jira.cms.gov/browse/PLT-176
Updated params for apply workflow to match updates in plan.
Missed these updates in #11.
See manual run here: https://github.com/CMSgov/ab2d-bcda-dpc-platform/actions/runs/7467371026. Apply is failing due to changes around permissions boundary, but the new params are being used.
None.
> PLT-176 Update opt-out-import apply params to match plan

- terraform/services/github-actions-runner/main.tf
- terraform/services/github-actions-runner/variables.tf
https://jira.cms.gov/browse/PLT-277
Reverts userdata change to allow for old image use
Re: https://github.com/CMSgov/ab2d-bcda-dpc-platform/pull/44#discussion_r1449252131
> PLT-277: Revert Userdata change

- .github/workflows/terraform-command.yml
Noticed while working on https://jira.cms.gov/browse/PLT-276
Add mgmt to help text
Small doc change so people know they can use the mgmt environment when running terraform.
Job already works with mgmt - see https://github.com/CMSgov/ab2d-bcda-dpc-platform/actions/runs/7747344314
None.
> PLT-276 Add mgmt environment to help text

- .github/workflows/opt-out-import-apply.yml
- .github/workflows/opt-out-import-plan.yml
- terraform/modules/lambda/main.tf
- terraform/modules/queue/main.tf
https://jira.cms.gov/browse/PLT-292
A couple of fixes to get applies clean on opt-out-import following the big changes in #51.
Just missed a couple of places where we were passing ARNs and parameter store values around that needed to be updated.
See plan checks. Tested apply locally.
None.
> PLT-292 Opt-out-import apply fixes

- terraform/modules/function/variables.tf
- terraform/services/opt-out-export/main.tf
- terraform/services/opt-out-import/main.tf
https://jira.cms.gov/browse/PLT-321
Added environment variables for the opt-out functions.
Setting these for the function to allow easy reference to the database host and BFD bucket for upload of export files.
See checks.
None.
> PLT-321 Add env vars for opt-out

- scripts/aws-assume-role.sh
https://jira.cms.gov/browse/PLT-390
Added aws-assume-role.sh in scripts.
While troubleshooting permissions errors for the AB2D workflow I had to assume roles for testing and felt the need for this script.
Tested locally, and linted with shellcheck.
None.
> PLT-390 Add aws-assume-role script

- .github/CONTRIBUTING.md
- .github/pull_request_template.md
https://jira.cms.gov/browse/PLT-469
A bit of polish in this round of updates to the PR template and CONTRIBUTING doc.
Seeking confirmation to propagate updates to the PR template and CONTRIBUTING doc in this repo to all AB2D, BCDA, and DPC repos.
@SJWalter11 Please review and confirm for updates to template for security implications.
There is a link to "contributing guidelines" when filing the PR, but it is small and easy to miss. See if you can find it in the screenshot below! I've moved the security implications language back into the PR template for higher visibility.
> PLT-469 Test and clean up for PR template and CONTRIBUTING doc

- .github/workflows/github-actions-oidc-provider-apply.yml
- .github/workflows/github-actions-oidc-provider-plan.yml
- .github/workflows/github-actions-role-apply.yml
- .github/workflows/github-actions-role-plan.yml
- .github/workflows/snyk-integration-apply.yml
- .github/workflows/snyk-integration-plan.yml
- .github/workflows/tfstate-apply.yml
- .github/workflows/tfstate-plan.yml
- terraform/backends/ab2d-mgmt.s3.tfbackend
[PLT-437](https://jira.cms.gov/browse/PLT-437)
backend for ab2d management was created and ab2d management account added to workflows
could not integrate Snyk to ab2d management ECR because ab2d backend was not yet configured
terraform plan ran locally.
>  PLT-437 Create and add ab2d-mgmt backend to workflow

- scripts/aws-assume-role.sh
https://jira.cms.gov/browse/PLT-366
Incorrect comment fixed in assume-role script.
Discovered while troubleshooting for PLT-366 that the comment in this script referred to the script it was copied from.
This comment makes sense to me now.
> PLT-366 Fix comment for assume-role script

- terraform/modules/queue/main.tf
[PLT-355](https://jira.cms.gov/browse/PLT-355)
batch_size set to 10
Terraform failed upon apply with error related to batch_size
> set batch_size to 1

- terraform/services/opt-out-export/main.tf
https://jira.cms.gov/browse/PLT-617
Updated handler and runtime for AB2D opt-out export function.
These changes have been made manually in AWS for the AB2D opt-out export function. This terraform change should adjust to match current resources.
See terraform plan in checks.
> PLT-617 Update ab2d handler and runtime

- .github/workflows/api-rds-plan.yml
- terraform/services/api-rds/main.tf
- terraform/services/api-rds/variables.tf
https://jira.cms.gov/browse/PLT-562=3
no change expected
Changes on the .tf files to make sure after import, terrafor plan do not show any breaking changes
comment will show the output of terraform plan
> importing ab2d-env rds

- .github/workflows/api-rds-apply.yml
- .github/workflows/api-rds-plan.yml
- terraform/services/api-rds/main.tf
https://jira.cms.gov/browse/PLT-724
Added dev environment to plan/apply action matrices
PLT-712 needs for us to update ab2d dev and test to Postgres 16, this is attempting to make that change from the same location. for both .
Validated locally with terraform plan; also verifying via terraform plan github action
> PLT-724 Apply api-rds service to ab2d dev

- terraform/services/api-rds/main.tf
https://jira.cms.gov/browse/PLT-724
Relevant to PLT-728 as well, this ticket completes step 2.2 of the work plan, creating the v16 parameter group to be consumed by the "green" deployment of ab2d dev and test
Following work plan, the new environments will need a separate parameter group to handle the v16 version of their parameters. While there are no breaking changes, this allows us to separate the parameters of v15 instances and v16 instances.
Local terraform plan, validated with GHA plan
> PLT-724 - Step 2.2 creating parameter group for v16 upgrade

- .github/workflows/api-rds-apply.yml
- .github/workflows/api-rds-plan.yml
- terraform/services/api-rds/main.tf
https://jira.cms.gov/browse/PLT-563
Added sbx and prod to workflow matrices for apply and plan
Following postgres 16 upgrade, this is intended to move management of RDS in ab2d fully into the platform repo
Local terraform plan & will verify with GHA terraform plan
> PLT-563 Updated workflows to add sbx and prod

- terraform/services/quicksight/athena.tf
- terraform/services/quicksight/iam.tf
- terraform/services/quicksight/main.tf
- terraform/services/quicksight/sql_templates/bulk_requests.sql.tfpl
- terraform/services/quicksight/sql_templates/everything_requests.sql.tfpl
- terraform/services/quicksight/sql_templates/group_requests.sql.tfpl
- terraform/services/quicksight/sql_templates/since_requests.sql.tfpl
- terraform/services/quicksight/sql_templates/total_benes_requested.sql.tfpl
- terraform/services/quicksight/sql_templates/uniq_benes_served.sql.tfpl
https://jira.cms.gov/browse/PLT-662
- Update commentary and definition for Athena Saved Queries (create or replace view)
- Update IAM permissions to include QuickSight actions where appropriate, including S3 CMK access
These changes were made to enable manual creation of QuickSight data sets, Analyses, and Dashboards
See Screen shots in Jira Ticket
> PLT-662: Establish Athena DataSets 

- .github/workflows/api-waf-sync-apply.yml
- .github/workflows/api-waf-sync-plan.yml
- terraform/services/api-waf-sync/README.md
- terraform/services/api-waf-sync/main.tf
- terraform/services/api-waf-sync/terraform.tf
- terraform/services/api-waf-sync/variables.tf
https://jira.cms.gov/browse/BCDA-8360
Update WAF Sync service to allow for BCDA
Update WAF Sync service to allow for BCDA
> BCDA-8360: Update WAF sync service for BCDA

- .github/workflows/api-rds-apply.yml
- .github/workflows/api-rds-plan.yml
- terraform/services/api-rds/main.tf
- terraform/services/api-rds/variables.tf
https://jira.cms.gov/browse/PLT-839
Added an ingress rule to the database security group to allow access from the management VPC.
Needed for workflows on GitHub runners to access the database.
See terraform plans in checks.
> PLT-839 Add mgmt cidr to db sg

- terraform/services/admin-aco-deny/main.tf
- terraform/services/admin-create-aco-creds/main.tf
Fix opensbx references
Fixes apply issue from merge of #173.
> BCDA-8630-fix-opensbx-references

- terraform/services/admin-create-group/main.tf
https://jira.cms.gov/browse/BCDA-8631
Updating name for opensbx to address apply failures.
> BCDA-8631: update the db_sg_name to handle sbx -> opensbx

- terraform/services/admin-create-aco-creds/main.tf
Added alias entry to get the key arn
Tf lint
> Add kms alias entry

- .github/workflows/api-rds-apply.yml
- .github/workflows/api-rds-plan.yml
- terraform/services/api-rds/data.tf
- terraform/services/api-rds/main.tf
- terraform/services/api-rds/variables.tf
https://jira.cms.gov/browse/PLT-564
modification made to code for bcda opensbx env and env added to plan and apply workflow
need to import bcda-sbx rds resources to platform repo terraform state 
output in GitHub actions for the opensbx env
> PLT-564: Apply shared terraform for database to BCDA dev, sbx, prod

- terraform/services/api-waf-sync/main.tf
https://jira.cms.gov/browse/PLT-890
Removed quotes around a url 
to correct a check error
All PR checks pass.
> [PLT-890] remove quotes around db_host to correct check failure

- .github/workflows/api-rds-apply.yml
- .github/workflows/api-rds-plan.yml
- terraform/services/api-rds/data.tf
- terraform/services/api-rds/main.tf
https://jira.cms.gov/browse/PLT-565
RDS shared terraform for 3 APIs configured and imported to terraform state
Apply shared terraform for database to DPC test, dev, sbx, prod
GitHub action workflow
> PLT-565: Apply shared terraform for database to DPC test, dev, sbx, prod 

- terraform/services/management-ecr/ab2d-ecr-lifecycle-policy.json
- terraform/services/management-ecr/main.tf
- terraform/services/services-ecr/ab2d-services-lifecycle-policy.json
- terraform/services/services-ecr/main.tf
- terraform/services/services-ecr/variables.tf
Adding ecr repo terraform for our greenfield accounts
We do not currently have ecr terraform we need to recreate our ECR repos for our new greenfield accounts.
Terraform plan
> Creating ECR repos for ab2d greenfield

- .github/workflows/api-rds-apply.yml
- .github/workflows/api-rds-plan.yml
- terraform/modules/bucket/main.tf
- terraform/modules/bucket/variables.tf
- terraform/modules/function/main.tf
- terraform/modules/function/outputs.tf
- terraform/modules/function/variables.tf
- terraform/modules/key/variables.tf
- terraform/modules/queue/main.tf
- terraform/modules/subnets/main.tf
- terraform/modules/subnets/variables.tf
- terraform/modules/topic/variables.tf
- terraform/modules/vpc/main.tf
- terraform/modules/vpc/variables.tf
- terraform/services/api-rds/data.tf
- terraform/services/api-rds/main.tf
- terraform/services/api-rds/variables.tf
- terraform/services/api-waf-sync/main.tf
- terraform/services/api-waf-sync/variables.tf
- terraform/services/opt-out-export/main.tf
- terraform/services/opt-out-export/variables.tf
- terraform/services/opt-out-import/main.tf
- terraform/services/opt-out-import/variables.tf
https://jira.cms.gov/browse/PLT-1040
Changes necessary for greenfield DPC dev environment setup
For pairing with DPC engineers on greenfield cutover process
We should see everything green :)
> PLT-1040 Initial changes for dpc dev greenfield env setup

- .github/workflows/tf-security-groups.yml
- terraform/services/security-groups/README.md
https://jira.cms.gov/browse/PLT-1060
Fixed apply in run-name and added note about security group rules.
Small follow-up on #225.
See checks.
> PLT-1060 Security groups service cleanup

- .github/workflows/opt-out-export-apply.yml
- .github/workflows/opt-out-export-plan.yml
- .github/workflows/opt-out-import-apply.yml
- .github/workflows/opt-out-import-plan.yml
- .github/workflows/tf-opt-out-export.yml
- .github/workflows/tf-opt-out-import.yml
https://jira.cms.gov/browse/AB2D-6757
Removing ab2d from the opt out CIs
We are moving this functionality to the ab2d repo.
> AB2D-6757 Remove ab2d from opt-out workflows

- .github/CODEOWNERS
- .github/workflows/sync-ab2d-ip-set.yml
- .github/workflows/sync-external-services-ip-sets.yml
- .github/workflows/sync-security-groups.yml
- README.md
- actions/aws-params-env-action/README.md
- actions/aws-params-env-action/package.json
- terraform/modules/platform/README.md
- terraform/modules/standards/README.md
- terraform/services/admin-aco-deny/terraform.tf
- terraform/services/admin-create-aco-creds/terraform.tf
- terraform/services/admin-create-aco/terraform.tf
- terraform/services/admin-create-group/terraform.tf
- terraform/services/api-rds/main.tf
- terraform/services/api-waf-sync/terraform.tf
- terraform/services/api-waf/README.md
- terraform/services/api-waf/terraform.tf
- terraform/services/bucket-access-logs/terraform.tf
- terraform/services/cclf-import/terraform.tf
- terraform/services/external-services-ip-sets/terraform.tf
- terraform/services/github-actions-oidc-provider/main.tf
- terraform/services/github-actions-role/main.tf
- terraform/services/github-actions-role/terraform.tf
- terraform/services/opt-out-export/terraform.tf
- terraform/services/opt-out-import/terraform.tf
- terraform/services/quicksight/terraform.tf
- terraform/services/security-groups/terraform.tf
- terraform/services/snyk-integration/terraform.tf
- terraform/services/tfstate/terraform.tf
https://jira.cms.gov/browse/PLT-657
references to ab2d-bcda-dpc-platform renamed to cdap
we are renaming the ab2d-bcda-dpc-platform repo to cdap
upon approval, ab2d-bcda-dpc-platform repo will be renamed to cdap and workflow re-ran, if successful PR merged if not ab2d-bcda-dpc-platform repo rename to cdap reverted while investigating why workflow failed
> PLT-657:Rename the public platform github repo

- terraform/services/github-actions-role/main.tf
https://jira.cms.gov/browse/PLT-657
fix formatting issues
formatting errors blocked apply
see checks
> PLT-657: fix formatting error

- terraform/modules/aurora/README.md
- terraform/modules/aurora/main.tf
- terraform/modules/aurora/outputs.tf
- terraform/modules/aurora/variables.tf
https://jira.cms.gov/browse/PLT-1208
Introduces a semi-opinionated Aurora module for CDAP customer usage.
Wider Aurora adoption and post-greenfield migration tasks.
- Applied and in-use across `ab2d` environments, including production
> PLT-1208: Aurora module for CDAP Customers

- terraform/modules/function/main.tf
https://jira.cms.gov/browse/...
Allow all kms decrypt permissions
To correct bcda incident
Manual change followup
> Allow lambdas to encrypt decrypt any resource.

- terraform/modules/bucket/main.tf
Removed sns topic from bucket module as it is un-used.
Revert #289 due to multiple attempts to create the topic under the same name.
See checks.
> PLT-1287 Removing topic as it is unused

- actions/setup-tenv/README.md
https://jira.cms.gov/browse/PLT-1363
Name steps in README on setup-tenv were updated
We are updating Name steps in README on setup-tenv to reflect the usage in BCDA and DPC
Readme is clearer.
> PLT-1363 : update Name steps in README on setup-tenv
