- scripts/aws-mfa-session.sh
No ticket - quick fix
Updated the aws-mfa-session script to use the default profile by default, and improved its error handling when, for example, jq is not installed on the machine.
In running the command on a new machine I saw some issues to be addressed.
Now runs with expected behavior on my laptop.
> Use default profile and improve error handling

- .github/workflows/github-actions-terraform-apply.yml
https://jira.cms.gov/browse/PLT-193
Added paths in the trigger on push to main.
This will constrain the trigger to only run on pushes that include paths relevant to the github actions runner terraform.
This should run on merge of this PR to main. We'll monitor future merges to ensure it only runs when needed.
> PLT-193 Add paths for push to main

- terraform/services/github-actions/main.tf
https://jira.cms.gov/browse/PLT-248
Minimum running time was set on GitHub Actions runners.
The scale-down lambda will sometimes terminate instances before they execute user data. We believe the slow startup is due to network wait on the Splunk forwarder. This is a temporary fix to avoid timing out. Longer term we can avoid needing user data by building our images, and possibly removing the Splunk forwarder from startup since these instances are sending logs to Splunk via cloudwatch.
See check for terraform plan. Minimum time raised from 5 to 10 minutes.
> PLT-248 Set minimum running time for GitHub Actions runners

- terraform/services/github-actions/main.tf
This is to update the runner size from t3.medium to t3.large due to memory constraints when running jobs.
> updating github runner instance size

- terraform/services/github-actions/main.tf
https://jira.cms.gov/browse/PLT-248
Set boot time instead of minimum running time, which should allow for installation of the actions agent before scale-down terminates the instance.
We were still seeing instances terminated at 5 minutes after the change in #24.
Will test by running jobs in ab2d-events and runner AMI creation following merge.
> PLT-248 Set boot time on runners

- .github/workflows/build-runner-images.yml
- packer/github-actions-runner/build.pkr.hcl
- packer/github-actions-runner/sources.pkr.hcl
- packer/github-actions-runner/variables.pkr.hcl
https://jira.cms.gov/browse/PLT-186
This PR contains fixes for the original implementation of the runner build workflow.
In order to test workflows, we must first merge them into the repo.
> PLT-186: Debugging 

- terraform/services/tfstate/.terraform.lock.hcl
- terraform/services/tfstate/README.md
- terraform/services/tfstate/main.tf
- terraform/services/tfstate/outputs.tf
- terraform/services/tfstate/variables.tf
- terraform/services/tfstate/versions.tf
https://jira.cms.gov/browse/PLT-279
Added a service to create resources for remote terraform state in AWS.
This is a bootstrap service to get us up and running with new resources for remote terraform state when needed. Currently useful as we initialize new backends for terraform in this platform repo, and should be useful when we transition teams to v4 AWS accounts.
Successfully applied to create new backends for remote state.
None.
> PLT-279 Add terraform for tfstate service

- .github/workflows/build-runner-images.yml
https://jira.cms.gov/browse/PLT-277
Switched out gold image AMI variables to pull in values from AWS Parameter Store. Also updated deploy role.
In an effort to keep secrets and variables in AWS instead of GitHub, I've set gold image params in the management account.
See checks. The build is failing due to an IAM PassRole issue with the bcda-packer role, likely because it isn't within the /delegatedadmin/developer/ path. We should still merge this and address that in another PR.
None.
> PLT-277 Switch gold image vars to aws params

- terraform/services/github-actions/main.tf
https://jira.cms.gov/browse/PLT-278
Modified path and resource to fix IAM policy for GitHub runner.
The permissions boundary for the deploy role won't allow management of policies outside of the /delegatedadmin/developer/ path, and I updated the deploy roles to include the application environment.
I had to delete the policy manually with an IAM user with direct access to the account. This should now apply cleanly once merged.
None.
> PLT-278 Fix GitHub runner policy

- terraform/services/github-actions-runner/main.tf
https://jira.cms.gov/browse/PLT-278
Allow the GitHub Actions runner role to retrieve parameters from the management account.
This allows for workflows like https://github.com/CMSgov/ab2d/blob/7bfa9085ade3537f5a2dd4203debd936aa1b4814/.github/workflows/unit-integration-test.yml to set shared ARTIFACTORY and SONAR params from the management account before assuming a role.
See checks for terraform plan. I'll test with the workflow above after merge.
None.
> PLT-278 Allow runner to get parameters

- terraform/services/github-actions-runner/main.tf
https://jira.cms.gov/browse/PLT-278
Add TagSession permission for the runner role.
The TagSession permission is also required to assume a role. Without it we get this error:
```
Error: Could not assume role with user credentials: User: arn:aws:sts::xxxxxxxxxx:assumed-role/github-actions-runner-role/i-xxxxxxxxxxxxx is not authorized to perform: sts:TagSession on resource: arn:aws:iam::xxxxxxxxxxxxx:role/delegatedadmin/developer/ab2d-dev-github-actions-deploy
```
I'll test in https://github.com/CMSgov/ab2d/pull/1306 once this is merged.
None.
> PLT-278 Add TagSession permission, required for assume

- .github/workflows/build-runner-images.yml
- packer/github-actions-runner/sources.pkr.hcl
https://jira.cms.gov/browse/PLT-285
Changes the role for building the images. The bcda-packer role is not within the permissions boundary.
None.
> PLT-285: Image building must not use bcda-packer role

- .github/workflows/build-runner-images.yml
- packer/github-actions-runner/sources.pkr.hcl
- terraform/services/github-actions-deploy-role/main.tf
https://jira.cms.gov/browse/PLT-285
Dropped iam_instance_profile from packer sources.
It appears that iam_instance_profile is only needed when using session manager to connect to the instance for building. 
https://github.com/hashicorp/packer-plugin-amazon/blob/2f6ed10096b416c957b7a33d198d19f5e6000971/docs-partials/builders/aws-session-manager.mdx#L10
See checks.
None.
> PLT-285 Drop instance profile from packer sources

- .github/workflows/build-runner-images.yml
- terraform/services/github-actions-runner/main.tf
https://jira.cms.gov/browse/PLT-277
Changing the image our runner image builds work on to the latest prebuilt runner image.
We successfully built an image using packer, but we are still using the old amzn2legacy image.
Image builds successfully.
> PLT-277: Switch GitHub runners to use the AMI we build

- .github/workflows/github-actions-deploy-role-apply.yml
- .github/workflows/github-actions-deploy-role-plan.yml
- .github/workflows/github-actions-oidc-provider-apply.yml
- .github/workflows/github-actions-oidc-provider-plan.yml
- .github/workflows/opt-out-import-apply.yml
- .github/workflows/opt-out-import-plan.yml
- .github/workflows/terraform-command.yml
- .github/workflows/tf-cmd.yml
- scripts/tf-apply-bcda-dpc
- scripts/tf-import-bcda-dpc
- terraform/modules/lambda/main.tf
- terraform/modules/lambda/variables.tf
- terraform/modules/queue/main.tf
- terraform/modules/queue/variables.tf
- terraform/modules/subnets/main.tf
- terraform/modules/subnets/variables.tf
- terraform/modules/vpc/main.tf
- terraform/modules/vpc/variables.tf
- terraform/services/github-actions-deploy-role/main.tf
- terraform/services/github-actions-deploy-role/variables.tf
- terraform/services/opt-out-import/main.tf
- terraform/services/opt-out-import/terraform.tf
- terraform/services/opt-out-import/variables.tf
- terraform/services/tfstate/main.tf
https://jira.cms.gov/browse/PLT-176
Fixes for workflows and infra to get opt-out-import working as I roll it out across accounts and environments. As part of this work, I've also abstracted out a generic "terraform command" reusable workflow that places constraints on terraform workspaces it's used on. Most notably, they must only require "app" and "env" variables.
Terraform has been successfully applied across AB2D, BCDA, and DPC environments. These are tweaks and refinements.
See workflow runs: https://github.com/CMSgov/ab2d-bcda-dpc-platform/actions/workflows/opt-out-import-apply.yml
None.
> PLT-176 Fixes to get opt-out-import apply working across environments

- .github/workflows/opt-out-import-apply.yml
- .github/workflows/opt-out-import-plan.yml
- terraform/modules/lambda/main.tf
- terraform/modules/queue/main.tf
- terraform/modules/subnets/outputs.tf
- terraform/modules/vpc/outputs.tf
https://jira.cms.gov/browse/PLT-287
Added dead letter queue to the queue module.
All standard SQS queues should have a dead letter queue to avoid endless retries of messages in the queue.
See checks for terraform plan.
None.
> PLT-287 Add dead letter queue to queue module

- .github/workflows/build-runner-images.yml
https://jira.cms.gov/browse/PLT-337
Specifies the version to build on, since the newest version fails on a node20 error.
Newest build of the Github Actions Runner AMIs failed, this should allow them to continue.
Build runs successfully.
> PLT-337: Set hashicorp/setup-packer version to v2.0.1

- .github/workflows/tfstate-apply.yml
- .github/workflows/tfstate-plan.yml
https://jira.cms.gov/browse/PLT-292
Dropped the `terraform state mv` commands from before and after the plan/apply in workflows.
These commands did their job in allowing us to apply tfstate terraform without destroying and creating tfstate buckets, and now they can be removed.
Plan checks should be clean aside from a couple where the access log buckets couldn't be created due to a "TooManyBuckets" error. Those should apply without issue on merge.
None.
> PLT-292 Drop state mv commands from tfstate workflows

- .github/workflows/opt-out-import-apply.yml
- .github/workflows/opt-out-import-plan.yml
https://jira.cms.gov/browse/PLT-292
Removed `terraform state mv` commands from opt-out-import workflows.
These state mv didn't work exactly as intended, since buckets still needed to be destroyed and created again, but they are no longer needed.
None.
> PLT-292 Drop mv commands in opt-out-import workflows

- .github/workflows/opt-out-export-apply.yml
- .github/workflows/opt-out-export-plan.yml
- .github/workflows/opt-out-import-apply.yml
- .github/workflows/opt-out-import-plan.yml
- terraform/modules/bucket/variables.tf
- terraform/modules/function/main.tf
- terraform/modules/function/outputs.tf
- terraform/modules/function/variables.tf
- terraform/services/opt-out-export/main.tf
- terraform/services/opt-out-import/main.tf
https://jira.cms.gov/browse/PLT-339
Updates to infra for integration tests.
As I put together integration tests in https://github.com/CMSgov/ab2d-lambdas/pull/87 I'm realizing updates that need to be made to our infra. The most impactful one is allowing assumption of the opt-out-import function role from GitHub OIDC, which I'm using in integration test workflows to trigger the lambda function by adding a test file to the BFD bucket.
I've also switched the scheduler trigger for the lambda function from an EventBridge Scheduler to a CloudWatch Event because I can then use `aws events put-events` to manually trigger the export function for testing.
None.
> PLT-339 Integration test infra

- terraform/modules/function/variables.tf
https://jira.cms.gov/browse/PLT-321
Set default for function timeout to 900 seconds, the max for lambda, rather than the built-in default of 3 seconds.
In testing opt-out-import and opt-out-export, engineers have requested this setting.
See checks.
None.
> PLT-321 Default timeout to lambda max

- terraform/modules/function/main.tf
https://jira.cms.gov/browse/PLT-321
- Allow retrieval of single parameters for lambda
The updated lambda in https://github.com/CMSgov/dpc-app/pull/2055 pulls the assume-role-arn as a single parameter from SSM. This adds the permission to retrieve a single parameter.
Made this change manually and was able to confirm successful lambda run.
Since this is a subset of the existing permissions (ssm:GetParamters), no real changes in security control/boundary here.
> PLT-321: Add ssm:GetParameter permissions to lambdas

- terraform/modules/function/main.tf
- terraform/modules/function/variables.tf
- terraform/services/opt-out-export/main.tf
- terraform/services/opt-out-import/main.tf
https://jira.cms.gov/browse/PLT-362
Set memory limit for the opt-out lambda functions as requested in PLT-362 for AB2D: 1GB for export, 2GB for import
This should allow for easy adjustment of the memory size limit for DPC and BCDA as well.
See checks.
None.
> PLT-362 Set function memory for ab2d

- terraform/services/opt-out-export/main.tf
changing handler from  gov.cms.ab2d.optout.OptOutHandler  to gov.cms.ab2d.attributionDataShare.AttributionDataShareHandler
> updating the handler for opt out export lambda

- terraform/services/opt-out-export/main.tf
https://jira.cms.gov/browse/DPC-3952
- Update memory for DPC export lambda
Tested with 128GB and the lambda stalled out while reading data from the database. After increasing the memory manually, was able to run the lambda successfully.
Looks like it currently requires 700MB, but would prefer to bump that to avoid issues in the future when DPC onboarding comes back online.
I think we will eventually want to improve the memory usage of our lambda — comparing with AB2D, we have significantly less data but are using comparable memory. Likely because we are loading all the data from the DB into Go structs, and then copying them into a byte buffer for writing to S3.
If any security implications apply, add Jason Ashbaugh (GitHub username: StewGoin) as a reviewer and do not merge this PR without …
> DPC-3952: Increase DPC export lambda memory

- terraform/services/opt-out-export/main.tf
https://jira.cms.gov/browse/PLT-362
Set ab2d opt-out lambda function to max memory (10GB).
AB2D export function currently uses a little under 5GB and runs for 28.6 seconds, but that may grow. Even at 10GB memory, running for 28.6 seconds costs approximately $0.00477, so cost concerns are low. We can adjust downward once usage is more established.
See checks.
None.
> PLT-362 Give AB2D export function max memory

- terraform/modules/bucket/main.tf
- terraform/modules/key/main.tf
- terraform/modules/key/variables.tf
https://jira.cms.gov/browse/PLT-390
Added access to the KMS key for cross-account read roles on S3 buckets.
Without this key access, promotion of function code was failing for AB2D: https://github.com/CMSgov/ab2d-lambdas/actions/runs/8426183564
Applied in ab2d-test environment and promotion now succeeds: https://github.com/CMSgov/ab2d-lambdas/actions/runs/8457881223
None.
> PLT-390 Add access to key for cross-account roles

- terraform/services/github-actions-role/main.tf
https://jira.cms.gov/browse/PLT-390
Allow the ct-ado admin role in each account to assume the GitHub Actions role we use for deploys.
In troubleshooting permissions for PLT-390 I found it quite useful to be able to assume the GitHub Actions role.
(How were the changes verified? Did you fully test the acceptance criteria in the ticket? Provide reproducible testing instructions and screenshots if applicable.)
None.
> PLT-390 Allow admin to assume github actions role

- .github/workflows/opt-out-export-apply.yml
- .github/workflows/opt-out-export-plan.yml
- .github/workflows/opt-out-import-apply.yml
- .github/workflows/opt-out-import-plan.yml
- .github/workflows/opt-out-test-apply.yml
- .github/workflows/opt-out-test-plan.yml
https://jira.cms.gov/browse/PLT-383
Dropped the sbx env across opt-out workflows.
In discussions with the application teams I confirmed there's no need for opt-out infrastructure in the sandbox environments.
This change will just keep future merges from applying in the sandbox environments. I'll destroy infra in these environments, then drop sbx-specific configuration from the terraform once this is merged.
None.
> PLT-383 Drop sbx env from opt-out workflows

- terraform/services/opt-out-export/main.tf
- terraform/services/opt-out-export/variables.tf
- terraform/services/opt-out-import/main.tf
- terraform/services/opt-out-import/variables.tf
- terraform/services/opt-out-test/variables.tf
https://jira.cms.gov/browse/PLT-383
Configuration specific to the sbx (sandbox) environment was removed from opt-out terraform.
The opt-out lambdas are not deployed to the sandbox environment, so configuration specific to that environment is not needed.
See checks, should be no change in terraform plan.
None.
> PLT-383 Remove sbx config from opt-out

- terraform/services/opt-out-export/main.tf
https://jira.cms.gov/browse/PLT-410
Updated schedule for the export function as follows:
- AB2D now runs weekly in prod
- All prod now run at 8/9pm ET depending on daylight savings
- All test now run at 8/9am ET
- All dev now run at 10/11am ET
This should bring the export schedule of attribution/request files in line with the ICD.
See checks for plans.
None.
> PLT-410 Update schedule for export function

- scripts/aws-assume-role.sh
N/A
Added pipefail option in aws-assume-role.sh script.
Errors from "aws sts assume-role" command in the script will now halt execution.
Tested locally.
None.
> Set pipefail on assume-role script

- packer/github-actions-runner/build.pkr.hcl
- packer/github-actions-runner/sources.pkr.hcl
N/A
Upped hop limit on the runner from 1 to 2.
Preemptively addressing this having seen the issue at https://github.com/philips-labs/terraform-aws-github-runner/issues/3821, which states that `http_put_response_hop_limit` must be increased to 2 for containers to access the instance metadata and access credentials for the instance profile.
See checks for image build.
None.
> Increase runner hop limit to 2

- terraform/services/opt-out-export/main.tf
https://jira.cms.gov/browse/AB2D-6038
Changed ab2d schedule from `prod = "cron(0 1 ? * TUE *)"` to `prod = "cron(0 1 ? * WED *)"`
AB2D’s Request file containing the beneficiary alignment and data sharing preferences information, provided to NGD on a weekly basis, every Tuesday between 20:00:00 hr and 22:00:00 hr ET.
The schedule `prod = "cron(0 1 ? * TUE *)" ` triggers the export lambda at 9pm ET on Monday because the schedule is in UTC
We want to have the same hours but the next day
See checks for terraform plan.
None.
> Change day in schedule for AB2D

- terraform/services/opt-out-import/main.tf
https://jira.cms.gov/browse/PLT-400
Lowered ab2d opt-out-import memory to 1GB.
In reviewing runs of the import function, memory peaks at roughly 250MB. My conclusion from research is that the JVM heap defaults to 25% of 1GB for machines with 1GB or more memory. We should therefore be able to change the memory from 2GB to 1GB with no effect on the function resources.
See checks for plan.
None.
> PLT-400 Lower ab2d opt-out-import mem to 1G

- .github/workflows/cclf-import-apply.yml
- .github/workflows/cclf-import-plan.yml
- terraform/services/cclf-import/README.md
- terraform/services/cclf-import/main.tf
- terraform/services/cclf-import/outputs.tf
- terraform/services/cclf-import/terraform.tf
- terraform/services/cclf-import/variables.tf
https://jira.cms.gov/browse/BCDA-8105
Adding Terraform infrastructure for cclf-import lambda functions.
Used existing opt-out import service as a template.
cclf-import lambda will only be used by BCDA.
This is partly a check of work. 
Not verified. If things look good from a code sense, testing can happen. Not sure on testing and how to perform it.
> BCDA-8105 Add cclf-import terraform infrastructure 

- terraform/services/opt-out-import/main.tf
Adds a check for bcda in order to correctly name the opt-out-import function handler.
https://jira.cms.gov/browse/BCDA-7898
Added a check for the app variable in order to change the handler name within the opt-out-import function.
Making it so that BCDA is properly supported for opt-out import.
None.
> BCDA-7898: Add bcda check for opt-out-import

- .github/CONTRIBUTING.md
- .github/pull_request_template.md
https://jira.cms.gov/browse/PLT-469
Updated the PR template.
We need to update PRs across the program for Jason's rolloff, and I'm taking advantage of the general update to address a few issues I've seen in our PRs:
1. People are skipping sections. These prompts may lessen that by more directly engaging the person filing the PR with questions.
2. People are leaving default text in PRs. Prompts are now in comments to avoid displaying default text.
3. The multiple-choice "Security Implications" section made it look like PRs were being merged with unfinished tasks. This update drops the "Security Implications" section and adds a CONTRIBUTING doc with some items borrowed from the [BFD template](https://github.com/CMSgov/beneficiary-fhir-data/blob/6a2c431592fbf385e115a738d4c43173c3a8fdbe/.githu …
> PLT-469 Update pull request template

- terraform/modules/queue/main.tf
- terraform/modules/queue/outputs.tf
- terraform/modules/queue/variables.tf
https://jira.cms.gov/browse/PLT-474
Queue visibility timeout set to default of 900.
With the function timeout set at 900 seconds but the queue visibility timeout at it's standard default of 30 we were [seeing this error](https://github.com/CMSgov/ab2d-bcda-dpc-platform/actions/runs/9404631602/job/25903957138#step:6:933) on apply: 
```
InvalidParameterValueException: Queue visibility timeout: 30 seconds is less than Function timeout: 900 seconds
```
This change updates the default for the queue module to match the function module. See some background at https://github.com/aws/serverless-application-model/issues/1424 where the reasons for why these must match is explained.
See plans in checks. I've also successfully applied in dev and test environments.
> PLT-474 Set default queue visibility timeout to 900

- terraform/services/cclf-import/main.tf
- terraform/services/opt-out-import/main.tf
https://jira.cms.gov/browse/BCDA-8208
- Rename handlers to bootstrap
Was looking at the lambda logs and saw some errors with trying to find the entrypoint. After reading the AWS documentation, I realized that it expects the zip file to have exactly one binary, which is specifically named bootstrap 😅
This was an oversight on my part — I thought if the handler was specified as cclf-import / opt-out-import here, it would look for that binary filename instead.
Changed manually in AWS Console and confirmed successful lambda initialization.
> BCDA-8208: Rename BCDA lambda handlers to bootstrap

- terraform/modules/bucket/main.tf
- terraform/modules/key/main.tf
- terraform/modules/key/variables.tf
https://jira.cms.gov/browse/PLT-355
Policy statements added to KMS key module for roles to use keys without having full admin access.
In looking into using customer-managed KMS keys while creating our access-log bucket, I realized we had set the policy on access/use roles too open.
@SJWalter11 This will tighten permissions around KMS keys created for opt-out functions in test environments.
See checks.
> PLT-355 Add policy statements for key user roles

- .github/workflows/build-runner-images.yml
https://jira.cms.gov/browse/PLT-338
Updated runners to the latest version to support node20.
Current Github Action Runner is failing due to node16 being depreciated and the runner version being outdated. Changes were made to have the runner up to date to be compatible with node20.
Request the changes to be reviewed and tested by the platform member.
> PLT-338 Update Github Actions Runners to support node20

- scripts/sg-ip-rules
https://jira.cms.gov/browse/PLT-460
Added sg-ip-rules script.
I've added this sg-ip-rules script as an example and something quick modifications could be made to in order to set security group rules quickly from the command line.
Used in filling in security group rules for zscaler-private and zscaler-public groups for PLT-460.
> PLT-460 Add sg-ip-rules script

- .github/workflows/cclf-import-apply.yml
- .github/workflows/github-actions-oidc-provider-apply.yml
- .github/workflows/github-actions-role-apply.yml
- .github/workflows/github-actions-runner-apply.yml
- .github/workflows/opt-out-export-apply.yml
- .github/workflows/opt-out-import-apply.yml
- .github/workflows/snyk-integration-apply.yml
- .github/workflows/tfstate-apply.yml
- .github/workflows/zscaler-security-groups-apply.yml
https://jira.cms.gov/browse/PLT-476
Added slack notification to all terraform apply failures in the workflow in ab2d-bcda-dpc-platform.
Notify the platform team in Slack when terraform apply fails to run.
Use a test github repo and slack channel and check if the notification is sent when the run fails.
> PLT-476 Notify platform channel on failed terraform apply in platform repo

- terraform/services/cclf-import/main.tf
n/a
Upped memory from 1024 to 2048 in BCDA CCLF lambda.
These changes were made because there are some CCLF files that exceed 1GB that are unable to be processed, after recent [improvements to memory usage being deployed.](https://github.com/CMSgov/bcda-app/pull/985) We have have manually changed the memory in the AWS console to 2048 and verified that it was adequate. This will mitigate future incidents where CCLF files fail to be ingested due to their size.
> BCDA: Up CCLF lambda memory

- .github/workflows/api-waf-dpc-apply.yml
Adds the terraform apply for dpc dev environment.
We'll need to have a tf apply to be able to utilize the terraform automatically.
See plan output: https://github.com/CMSgov/ab2d-bcda-dpc-platform/actions/runs/10583065125/job/29324204318#step:6:21
> PLT-585 Add api-waf apply for dpc dev

- .github/workflows/external-services-ip-sets-apply.yml
- .github/workflows/external-services-ip-sets-plan.yml
- terraform/services/external-services-ip-sets/README.md
- terraform/services/external-services-ip-sets/main.tf
- terraform/services/external-services-ip-sets/terraform.tf
Add WAF IP sets for external services, including Zscaler and New Relic.
In setting up the new WAF for DPC dev, we realized the need for shared IP sets within an account that would contain IPs for external services. This terraform creates those IP sets but leaves management of the addresses/ranges within them up to other processes (manual for now, automated from CIDRs in the private repo in the future).
> PLT-585 External services IP sets

- terraform/services/external-services-ip-sets/main.tf
Dropped scope from the names of external-services IP sets.
Small addendum to #116 because it turns out IP sets in different scopes (regional vs cloudfront) can have the same name.
> PLT-585 Drop scope from external-services IP set names

- .github/workflows/api-waf-apply.yml
- terraform/modules/firewall/main.tf
- terraform/modules/firewall/variables.tf
- terraform/services/api-waf/main.tf
Added the ability to set IP sets in the firewall module, and added an IP set for customers in the api-waf service. Also referenced the external-services IP set created in #116 and #117.
This will associate terraform-managed IP sets with the WAF for each API (starting with DPC dev environment). CIDRs in these IP sets will be managed outside of terraform.
> PLT-585 IP sets for the api-waf service

- .github/workflows/api-waf-apply.yml
- .github/workflows/api-waf-plan.yml
- terraform/modules/firewall/main.tf
This adds an override to the AWSManagedRulesCommonRuleSet's CrossSiteScripting_BODY check to allow DPC to send HTML in the requests to certain endpoints of their API.
This should fix the failing smoke tests DPC has in the dev environment. We found that this rule had been blocking requests to certain endpoints.
Terraform plan should pass and the DPC smoke test in DEV should pass once this is applied.
> PLT-585: Add override to aws-common ruleset for XSS check

- terraform/modules/firewall/main.tf
Adds an override block for the `SizeRestrictions_BODY` AWS provided WAF rule.
After moving to batch requests to avoid hitting the rate limit WAF rule, we foudn that the requests would be too large for AWS' provided WAF rules.
DPC smoke tests should pass after this is applied.
> PLT-585: Override size requirement WAF rule

- .github/workflows/api-waf-apply.yml
- .github/workflows/api-waf-plan.yml
- terraform/modules/firewall/main.tf
- terraform/services/api-waf/main.tf
https://jira.cms.gov/browse/PLT-503
Adds test and sbx environments to the DPC WAF configuration
These are changes made as a part of the overall WAF migration work.
Once this is applied, we should see the Web ACL configurations show up with the placeholder IP sets. We'll need to manually update them in AWS, and then reapply once we remove the association with the security group on ingress.
> PLT-503: Add test and sandbox environments to DPC WAF plan and apply

- .github/workflows/api-waf-apply.yml
- terraform/services/api-waf/main.tf
https://jira.cms.gov/browse/PLT-504
This adds the BCDA dev environment to the apply workflow of the new WAF configuration.
We're moving all apps to WAF for IP filtering. This should alleviate some of the issues we have with security groups and maintaining our CIDR whitelists.
BCDA dev should be able to be reached on the VPN, but no other traffic should be let through. The BCDA team may need to add CIDR ranges to the new IP-set that will be created. We'll also need to remove the association to the dev WAF and security group in place in the bcda-ops repo: https://github.com/CMSgov/bcda-ops/pull/1114
> PLT-504: Add BCDA dev environment to WAF configuration

- .github/workflows/github-actions-runner-apply.yml
https://jira.cms.gov/browse/PLT-671
Dropped unused terraform variable and updated slack channel for alerts.
We saw an error in the apply with the recent merge to main. See the run at https://github.com/CMSgov/ab2d-bcda-dpc-platform/actions/runs/11405915837/job/31738457455. Also, the alert was sent to the cdap-users channel when it should go to cdap.
See manual run of apply workflow at https://github.com/CMSgov/ab2d-bcda-dpc-platform/actions/runs/11408130895/job/31745654912.
> PLT-671 Fix github-actions-runner-apply workflow

- .github/workflows/api-waf-apply.yml
- terraform/services/api-waf/main.tf
https://jira.cms.gov/browse/PLT-650
Adds BCDA to the apply workflow and updates a comment with a link to the decision log
We're continuing our rollout of the new WAF config to the BCDA test and sandbox environments.
Smoke tests should succeed in each environment and network traffic should remain the same. To be merged after https://github.com/CMSgov/bcda-ops/pull/1118 is approved and deployed to the environments.
> PLT-650: Add BCDA to apply matrix for WAF config

- terraform/services/api-rds/main.tf
https://jira.cms.gov/browse/PLT-724 
Changing rds.logical_replication from immediate to pending-reboot apply method
AWS/Hashicorp documentation was unclear that the parameter was static and could not be applied immediately, and verification via plan/github action was misleading as the plan showed no errors, but the apply did error.
Successful plan locally, validated all "immediate" apply method parameters referenced are dynamic by postgres documentation
> PLT-724 fixed parameter error for rds.logical_replication

- terraform/modules/firewall/main.tf
https://jira.cms.gov/browse/PLT-635
Adds an override for requests lacking the User-Agent HTTP header
BCDA receives a majority of their requests from automated systems that lack this header, and do not require it in the previous iteration of the WAF.
Requests with no user-agent header (eg., scheduled FHIR scan requests) should pass through the WAF.
> Override NoUserAgent_HEADER block on WAF config

- terraform/services/github-actions-role/main.tf
https://jira.cms.gov/browse/PLT-755
Added ab2d-website repo to list of repos for role access.
This allows GitHub runners for the ab2d-website repo workflows to access roles in AWS.
See checks for terraform plan. Will be tested with workflows in the ab2d-website repo after merge.
> PLT-755 Add ab2d-website repo for OIDC access

- terraform/services/quicksight/iam.tf
- terraform/services/quicksight/main.tf
https://jira.cms.gov/browse/PLT-674
APPLY at merge of original PLT-674 failed due to policy resource reference mistakes (key alias vs ARN) and problematic naming of an S3 bucket.
These changes attempt to resolve.
see above
plan succeeds
> PLT-674 fix: policy resource references and bucket naming

- terraform/services/quicksight/athena.tf
- terraform/services/quicksight/main.tf
https://jira.cms.gov/browse/PLT-674
change Athena database bucket reference from ARN to ID
Previous branch PLT-674-fix failed to apply completely
see above
> PLT-674 Second Rd Apply Fixes - Athena

- terraform/services/api-rds/main.tf
https://jira.cms.gov/browse/PLT-728
Updating TF to match current AWS state per Postgres 16 upgrade work plan
Due to technical issues with Postgres 16.4 upgrade there were some settings changed via console and this pull is intended to realign terraform with the intended settings.
Local TF plan & TF refresh-only updates for state file; also validating via GHA plan
> PLT-728 update state and tf to postgres upgrade

- terraform/services/api-waf-sync/main.tf
https://jira.cms.gov/browse/DPC-4415
DB_HOST parameter set from AWS
Added permission to use ListIpSets
The code was failing because it was missing an environment variable and lacking a permission.
Applied locally and it works now
> Additions for api-waf-sync

- terraform/modules/firewall/variables.tf
- terraform/services/api-waf/main.tf
https://cmsgov.slack.com/archives/C04UG13JF9B/p1733939290774959
Bumping DPC rate limit to 3000requests/5min
DPC is seeing some customers get timed out
DPC rate limit rule should be changed, all others should stay the same
> Bump DPC rate limit

- .github/workflows/aws-params-env-action-check-dist.yml
https://jira.cms.gov/browse/PLT-832
Changed upload-artifacts version to v4.
The current upload-artifacts version is being sunset, so we will have to update the version to v4.
Workflow should run without failures
> PLT-832: Update upload-artifacts from v3 to v4

- terraform/services/github-actions-role/main.tf
https://jira.cms.gov/browse/PLT-851
Added repos for github-actions-role permissions.
In creating workflows for the bcda-ssas-app repo, the BCDA team found they could not assume the github actions IAM roles in our accounts. I noticed the bcda-static-site and dpc-static-site repos were also missing from the list, so added those as well in anticipation of workflows there.
See checks for terraform plans.
> PLT-851 Add repos to github-actions-role

- .github/workflows/api-waf-apply.yml
https://jira.cms.gov/browse/PLT-505
Adds AB2D target environments to the matrix for deployment.
We have to add the environments to the matrix in a way that ensures we keep the existing environments' for other teams in place.
We will deploy this after the changes in the AB2D ops repo are deployed: https://github.com/CMSgov/ab2d-ops/pull/300
> PLT-505: Add AB2D DEV and TEST to WAF-apply environment matrix

- terraform/services/opt-out-export/main.tf
https://jira.cms.gov/browse/DPC-4460
Configuration of dpc opt out export memory changed from 1024 to 2048
Our lambda on prod started failing with `Error: Runtime exited with error: signal: killed`, and manually increasing to 2048 fixed it.
Upped manually; lambda has run successfully since.
> Increase memory for dpc opt out export lambda

- .github/workflows/admin-aco-deny-apply.yml
- .github/workflows/admin-aco-deny-plan.yml
- .github/workflows/api-waf-sync-apply.yml
- .github/workflows/api-waf-sync-plan.yml
- terraform/services/admin-aco-deny/README.md
- terraform/services/admin-aco-deny/main.tf
- terraform/services/admin-aco-deny/outputs.tf
- terraform/services/admin-aco-deny/terraform.tf
- terraform/services/admin-aco-deny/variables.tf
https://jira.cms.gov/browse/BCDA-8626
Add supporting terraform for new BCDA lambda (admin task Deny ACOs), mostly copy pasted from similar lambdas.
New BCDA lambda.  Part of the move from jenkins.
Local terraform lint
> BCDA-8626: Add supporting terraform for new BCDA lambda

- terraform/services/api-waf/main.tf
https://jira.cms.gov/browse/PLT-820
Removed the line making BCDA's limit 1000/5min
https://cmsgov.slack.com/archives/CHG7Q7XNH/p1734444527725299?thread_ts=1734019554.318099&cid=CHG7Q7XNH
> @ Grant Freeman let's 10x BCDA's rate limit from 300 requests / 5 minutes to 3000 requests / 5 minutes to match DPC. This will help us:
> 1. meet the needs for Maryland TCoC above (many file downloads for 1 entity)
> 1. address a previous request from Aledade (many entities for 1 IP address)
After discussion with the BCDA team, we decided on 1000requests / 5 minutes instead.
This should be verifiable by checking the rate limit rule no the BCDA WAFs
> PLT-820: Increase BCDA rate limit to 3000

- terraform/services/github-actions-runner/main.tf
https://jira.cms.gov/browse/PLT-754
Ensure the runner container runs as root.
As noted in https://github.com/actions/checkout/issues/956, GitHub still expects runner containers to run as root. Permissions around the actions/checkout step break in a number of ways if this is not set.
Will apply and test in the job currently failing on https://github.com/CMSgov/bcda-app/pull/1031.
> PLT-754 Ensure runner runs as root

- terraform/services/github-actions-runner/main.tf
https://cmsgov.slack.com/archives/C04UG13JF9B/p1737999040128209
Increases the size of the volumes on the runners
DPC is having docker image build failures due to running into memory issues
DPC builds should pass after this is merged, we may see image snapshots start to increase in size as well
> Increase size of EBS volumes on GHA Runners

- packer/github-actions-runner/variables.pkr.hcl
- terraform/services/github-actions-runner/main.tf
https://jira.cms.gov/browse/PLT-884
Changes instance size for runners to t3.xlarge
Application engineers expect self-hosted runners to match github-hosted runners for compute.
See terraform plan in checks, and see apply on merge to ensure successful infra update.
> PLT-884 Increase compute for GHA runners

- packer/github-actions-runner/sources.pkr.hcl
https://jira.cms.gov/browse/PLT-884
Specifies volume size for GHA runner AMIs
We are still not utilizing the full disk space of the runners. This change will double the spacce and potentially unblock the jobs that are seeing disk usage errors.
Workflows utilizing the GHA runners should no longer fail due to storage errors.
> PLT-884: Add config for block storage for GHA runner AMI

- terraform/services/github-actions-runner/main.tf
https://jira.cms.gov/browse/PLT-895
Overrides the default 3 concurrent runners to 12 to allow for long-running jobs to not block runners being assigned.
See relevant slack thread: https://cmsgov.slack.com/archives/C04UG13JF9B/p1738176789390989?thread_ts=1737999040.128209&cid=C04UG13JF9B
This should allow for workflows with multiple jobs to be run in parallel without blocking.
Teams should see their runners pick up more jobs in workflows.
> PLT-895: Increase Concurrent GHA Runners

- .github/workflows/api-waf-apply.yml
- .github/workflows/api-waf-plan.yml
https://jira.cms.gov/browse/PLT-634
Adds BCDA PROD to environment matrix for the shared WAF module rollout.
This will enable the WAF in the PROD environment and filter all incoming traffic.
After https://github.com/CMSgov/bcda-ops/pull/1128 is merged, we should be able to merge this PR to enable the WAF module in production. I'll then check for traffic/connection issues, and fail forward (create new PRs to address) if necessary.
> PLT-634: API WAF - Add BCDA PROD to environment matrix

- .github/workflows/admin-aco-deny-apply.yml
- .github/workflows/admin-aco-deny-plan.yml
- .github/workflows/admin-create-aco-creds-apply.yml
- .github/workflows/admin-create-aco-creds-plan.yml
- terraform/services/admin-aco-deny/main.tf
- terraform/services/admin-aco-deny/variables.tf
- terraform/services/admin-create-aco-creds/README.md
- terraform/services/admin-create-aco-creds/main.tf
- terraform/services/admin-create-aco-creds/outputs.tf
- terraform/services/admin-create-aco-creds/terraform.tf
- terraform/services/admin-create-aco-creds/variables.tf
Add BCDA service and workflows for Admin Create ACO Credentials lambda.
Part of moving off jenkins.  This service supports the BCDA Admin Create ACO Credentials lambda which creates a credentials file for an ACO in s3.
TF validation script.
> BCDA-8630: Add create admin ACO creds service and workflows

- packer/github-actions-runner/build.pkr.hcl
https://jira.cms.gov/browse/PLT-897
Adds a new provisioner to the packer build.
We need to actually resize the volumes for the jobs to have enough space on disk to succeed. We're embedding resizing of the volumes into packer.
Jobs should get past the disk space issues.
> PLT-897: Add new shell provisioner for resizing volumes

- .github/workflows/admin-create-aco-apply.yml
- .github/workflows/admin-create-aco-plan.yml
- terraform/services/admin-create-aco/README.md
- terraform/services/admin-create-aco/main.tf
- terraform/services/admin-create-aco/outputs.tf
- terraform/services/admin-create-aco/terraform.tf
- terraform/services/admin-create-aco/variables.tf
In order for BCDA to move off of Jenkins we need a new lambda to handle the admin task of Create ACO. This terraform service will handle the IaC side.
https://jira.cms.gov/browse/BCDA-8629
Added a new service for the platform
Infrastructure needed to be made in order to handle the new lambda.
Terraform plan
> BCDA-8629: Add infrastructure for Create ACO Admin Task

- terraform/services/admin-create-aco-creds/main.tf
Added kms:ListAliases role access for admin aco create creds lambda.
Part of moving off jenkins.  This lambda needs to access kms aliases in order to retrieve a specific keyID in order to allow access to put creds in a specific bucket.
Terraform fmt
> Add kms access for lambda

- terraform/services/admin-create-aco-creds/main.tf
Add kms GenerateDataKey policy to lambda.
This lambda needs to be able to securely put s3 objects.
Tf lint
> Add generate data key policy

- actions/setup-tfenv-terraform/action.yml
https://jira.cms.gov/browse/PLT-948
Adds a check to see if TF is already installed on the machine before cloning.
[This thread](https://cmsgov.slack.com/archives/C04UG13JF9B/p1741287498094549) brought up an issue where the TF installation step was hitting errors because a prior run had already installed the necessary files. Git clone does not allow for overwriting, so the operation would fail with an error.
We should see runs no longer fail due to existing tfenv directories when using the installation action.
> PLT-948: Bugfix for TF install action

- terraform/services/github-actions-runner/main.tf
https://jira.cms.gov/browse/PLT-917
The Github runner machine type was changed from t3.xlarge to m6i.xlarge.
As per the analysis documented in a comment on PLT-917 this change is being made in order to gain the benefits of significantly faster network speeds and also non-burstable CPU, which together should bring the overall execution time of workloads run on self-hosted runners closer to being on par with the execution times being observed when the same workloads are run on Github-hosted runners.
Validation so far has been to compare the documented specs of the t3.xlarge and m6i.xlarge and confirm the performance gains that can realized by changing the machine type.
> PLT-917: Changing runner machine type to m6a.xlarge for better performance

- actions/setup-tfenv-terraform/action.yml
https://jira.cms.gov/browse/PLT-948
Changes the git clone method to one where we clone to a temp directory to get around git clone's limitation of needing the directory to be empty
After implementing a fix where we check to see if tfenv is already installed, we were still getting errors with `git clone` because the directory already existed.
Workflows should pass and not be stopped by previous tfenv installations.
> PLT-948: Add clone to temp directory

- packer/github-actions-runner/build.pkr.hcl
https://jira.cms.gov/browse/PLT-905
Adds installation commands for the latest release of docker compose for the GHA runners packer build.
Several teams use containerized tests in their workflows, this will allow them to run without requiring the teams to specify a docker compose installation in every workflow.
Compose should be installed by default on all runner images after this is merged and applied.
> PLT-905: Add Docker Compose install to packer build for GHA runners

- .github/workflows/ab2d-ip-sets-sync.yml
- scripts/waf-ip-set-sync.sh
https://jira.cms.gov/browse/PLT-508
Adds automation in the form of a workflow and associated script for automating AB2D WAF IP set updates.
AB2D needs an automated way to keep their IP sets up to date, this aims to do that. This workflow will eventually run on a cron schedule the team sees fit (likely daily/multiple times a day). The method is as follows (modeled off of the steps found [here](https://repost.aws/knowledge-center/maintain-waf-ipsets-using-cli)):
1. IPs are stored in the `cdap-private` repo.
2. Workflow is triggered by cron.
3. IPs are loaded into JSON that is digestible by AWS `update-ip-set` command. ([docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/wafv2/update-ip-set.html))
4. Existing IP sets are fetched with `get-ip-set` to get a lock token …
> PLT-508: AB2D WAF IP Set Sync Workflow

- .github/workflows/api-waf-apply.yml
https://jira.cms.gov/browse/PLT-709
Adds ab2d to the apply workflow matrix.
As part of the rollout of the WAF shared service to AB2D prod, we have to add the environment to the terraform apply for the service.
Once this and https://github.com/CMSgov/ab2d-ops/pull/313 are merged, the new WAF shared service will be associated with the existing load balancer, and handle all IP filtering for the AB2D API.
> PLT-709: Add AB2D Prod to Apply Matrix

- .github/workflows/ab2d-ip-sets-sync.yml
- scripts/waf-ip-set-sync.sh
https://jira.cms.gov/browse/PLT-508
Adds the prod environment to the action's environment matrix.
When the initial PR for PLT-508 was merged, it only included dev and test for testing purposes, once those pass, we should be able to merge this PR in, but only after the WAF shared service has been rolled out to AB2D production.
The script should update the WAF IP sets for each environment with the current state of the allowed_ips list in the private repo.
> PLT-508: Add Prod environment to matrix

- packer/github-actions-runner/install-runner.sh
This is to remove the workaround we needed for openssl 3.0.8
bugfix
This is to remove the workaround we implemented for openssl 3.0.8
Amazon released the latest openssl 3.2.2 and it looks like we are hitting errors potentially due to this workaround.
We will merge and test revert if it does not work.
> Remove openssl workaround

- .github/workflows/external-services-ip-sets-sync.yml
- scripts/waf-ip-set-sync-external-services.sh
https://jira.cms.gov/browse/PLT-506
- Added new file external-services-ip-sets-sync.yml runner file
- Added new file waf-ip-set-sync-external-services.sh to run the sync via the AWS CLI.
- Added new file allowed-ips.txt under cdap-private/ip-sets/external-services with IP sets taken from BCDA account.
These changes are intended to establish a framework for syncing the external-services IPSets from various accounts and environments to a file of CIDR IP ranges in the CDAP private repo. This workflow is currently configured to be manually run, but can easily be reconfigured to run on a schedule or on an update to the CDAP private repo.
These changes were validated by running a GHA workflow against the AB2D IMPL and BCDA/DPC accounts us-east-1 regions.
> PLT-506: External services WAF IP sync

- actions/setup-tfenv-terraform/action.yml
https://jira.cms.gov/browse/PLT-930
Pins a specific release of the tfenv project for use in Github actions.
We're pinning the version of this utility until we can move to a higher confidence installation method. See comments in ticket.
We're already using this version of [tfenv](https://github.com/tfutils/tfenv), it will just prevent automatic updates from happening in the future.
> PLT-930: Pin tfenv release version

- terraform/modules/bucket/main.tf
- terraform/modules/bucket/variables.tf
https://jira.cms.gov/browse/PLT-890
toggle bucket characteristics based on legacy variable
For backwards compatibility with non-greenfield deployments
Upon terraform apply in the new vpcs, backend buckets are created
> [PLT-890] Add bucket config toggle for legacy variable

- terraform/services/opt-out-export/main.tf
[https:/https://jira.cms.gov/browse/PLT-890
/jira.cms.gov/browse/PLT-890](https://jira.cms.gov/browse/PLT-890)
Added new security group rule type per guidance from Hashicorp.  https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_security_group_ingress_rule
Changes are to fix workflow failures for dpc-dev
Green workflow:  opt-out-export apply terraform  for DPC-DEV
> [PLT-890] resource type change per hashi guidance

- actions/setup-tfenv-terraform/action.yml
https://jira.cms.gov/browse/PLT-891
Reverts changes made in a previous PR that broke the tfenv install step
We started seeing failures from some teams after we made a change that broke permissions for the tfenv install https://github.com/CMSgov/ab2d-bcda-dpc-platform/pull/214
Teams should see the tfenv step function as expected after this is merged
> Revert change to fix tfenv install

- terraform/modules/bucket/main.tf
- terraform/modules/bucket/variables.tf
- terraform/modules/function/main.tf
https://jira.cms.gov/browse/PLT-1040
This adds back an optional parameter that references the name of the bucket passed in through the `function` module. 
We removed the SSM Parameter for the bucket since it was creating parameters in every environment on legacy as well as greenfield. This removal makes greenfield development a bit harder as we cannot interpolate the bucket name by by App and Environment during deployment.
This should allow DPC to continue greenfield development and deployment
> PLT-1040: Add bucket SSM Parameter back to Greenfield Environments

- terraform/services/api-rds/data.tf
- terraform/services/api-rds/main.tf
- terraform/services/api-rds/variables.tf
- terraform/services/service-security-groups/main.tf
- terraform/services/service-security-groups/variables.tf
https://jira.cms.gov/browse/PLT-1008
In short, this PR brings about necessary changes to run in the greenfield environments along with some bug fixes that weren't revealed until now:
- fix the AWS secret lookup resolution; document
- make use of default aws/rds KMS keys
- fix issues where bcda terraform and _this_ module both attempt to create local hosted zones
- introduce a number of `rds-api` module dependency security groups to `service-security-groups` for greenfield
- make required variables in `rds-api` optional using lookups (mgmt cidr) or ignoring them (jenkins subnets)
- annotate and disable certain resources in greenfield to allow this module to apply
This is the first time we've had the opportunity to use these modules to instantiate environments.
Naturally, there were a …
> PLT-1008: Support API RDS in Greenfield

- .github/workflows/sync-external-services-ip-sets.yml
- .github/workflows/sync-security-groups.yml
https://jira.cms.gov/browse/PLT-1060
Added sync-security-groups workflow. Also made a small fix on sync-external-services-ip-sets.
This workflow should allow us to sync rules on security groups from CIDRs in cdap-private. Currently syncs zscaler-private and zscaler-public.
Successful workflow runs at https://github.com/CMSgov/ab2d-bcda-dpc-platform/actions/runs/15073061359 and https://github.com/CMSgov/ab2d-bcda-dpc-platform/actions/runs/15073825193. Security groups checked and all rules are present.
> PLT-1060 security group sync workflow

- .gitignore
- .terraform-docs.yml
- terraform/modules/platform/README.md
- terraform/modules/platform/main.tf
- terraform/modules/platform/outputs.tf
- terraform/modules/platform/terraform.tf
- terraform/modules/platform/variables.tf
https://jira.cms.gov/browse/PLT-1033
Introduces a child module for commonly referenced security groups, iam roles, subnets, and other basics that any consuming module might otherwise lookup for itself with a separate collection of data sources and input parameters. 😬 
This will help define the standards by which the CDAP customers operate, including setting a baseline for default tags.
Because this is for greenfield only, I've been able to make use of this child module in a limited capacity in the AB2D core service module–it works!
> PLT-1033: Introduce a platform child module

- .github/workflows/tf-api-waf.yml
https://jira.cms.gov/browse/PLT-805
Fixed string interpolation in run-name for tf-api-waf workflow.
Runs were showing as "tf-api-waf true" instead of "tf-api-waf apply".
See run with correct name at https://github.com/CMSgov/ab2d-bcda-dpc-platform/actions/runs/15189772084.
> PLT-805 Fix run-name interpolation

- .github/workflows/tf-bucket-access-logs.yml
- .github/workflows/tf-external-services-ip-sets.yml
- .github/workflows/tf-github-actions-role.yml
- .github/workflows/tf-security-groups.yml
https://jira.cms.gov/browse/PLT-891
Fixes the trigger on the github-actions-role workflow and run names across tf workflows.
Follow-up on #214 when trigger and run-name issues were noticed.
See checks, and confirm correct behavior on merge to main.
> PLT-891 Fix trigger and run names

- terraform/services/api-waf/main.tf
https://jira.cms.gov/browse/PLT-1093
Fix for WAF terraform to get the load balancer for AB2D.
The data call for the load balancer in the api-waf terraform did not find the newly created ab2d load balancer in greenfield.
See checks. Applied with https://github.com/CMSgov/ab2d-bcda-dpc-platform/actions/runs/15211384139/job/42786198048
> PLT-1093 Add -api suffix to ab2d lb data call

- .github/workflows/tf-api-waf-sync.yml
https://jira.cms.gov/browse/PLT-1031
Removed DPC prod environment from api-waf-sync workflow
We don't actually run the WAF sync in the prod environment on legacy. It was added in error to the new workflow for greenfield.
WAF sync function should not be operating on DPC GF prod environment
> PLT-1031: Remove DPC Prod from api-waf-sync lambda terraform

- scripts/prewarm.sql
https://jira.cms.gov/browse/PLT-1119
Added SQL script for running prewarm across tables.
Following restore of a PostgreSQL database in RDS, initial queries can be slowed by lazy loading of data from S3. This script follows [AWS recommendations](https://aws.amazon.com/blogs/database/amazon-rds-snapshot-restore-and-recovery-demystified/) to use the pg_prewarm extension to read blocks, effectively loading data in preparation for queries. We were previously running VACUUM FULL over databases following a restore, which took several hours unnecessarily rewriting tables and indexes.
To ensure data readiness following a restore, this could be followed up by SELECT queries specific to each team's data for common API queries.
Run on a restore of the bcda-prod db, this script takes roughly 15 …
> PLT-1119 Add prewarm script

- scripts/prewarm.sql
https://jira.cms.gov/browse/PLT-1119
Updated the warmrels table select to not include tables without relpages. 
Tables without relpages should not need to be prewarmed, and this avoids including the warmrels table itself in the list, which was resutling in `ERROR:  cannot access temporary tables of other sessions`.
Tested on ab2d dev database.
> PLT-1119 Select tables with relpages

- .github/workflows/sync-external-services-ip-sets.yml
https://jira.cms.gov/browse/PLT-1131
Adds two files, one for each account, to the external-services sync workflow.
When applied, this will add the public NAT gateway IPs to the external-services allowlist to let the teams reach their public load balancers from resources on the same account.
Once this is applied, we should see the IPs added in https://github.com/CMSgov/cdap-private/pull/8 in the external-services IP set.
> PLT-1131: Add files for NAT gateways to external-services sync workflow

- .github/workflows/tf-api-rds.yml
- terraform/services/api-rds/data.tf
- terraform/services/api-rds/main.tf
https://jira.cms.gov/browse/PLT-1040
Fix the run-name to print "tf-api-rds apply" when inputs.apply is true. Get secrets for the database from a standard secret path. Dropped ab2d from the workflow by request.
This is a follow-up on #240 to address issues seen in applying.
See apply at https://github.com/CMSgov/ab2d-bcda-dpc-platform/actions/runs/15591371735.
> PLT-1040 Follow-up fixes on api-rds

- .github/workflows/sync-external-services-ip-sets.yml
https://jira.cms.gov/browse/PLT-1131
Fixes an issue where we were including non-prod NAT Gateway IPs in the production environment and vice-versa.
We'd like for our team's public load balancers to be available to resources on the same account, but not non-prod<->prod.
Runs cleanly: https://github.com/CMSgov/ab2d-bcda-dpc-platform/actions/runs/15593497148
> PLT-1131: Add prod/non-prod conditional to external-services sync

- terraform/services/admin-create-aco-creds/main.tf
https://jira.cms.gov/browse/BCDA-9143
The aco creds output bucket name is changed for Greenfield.
The IAM policies for the lambda are updated to remove encryption/KMS rules for Greenfield.
Our bucket naming strategy and s3 encryption management have changed for greenfield, and the Create ACO Creds lambda must be updated accordingly. The legacy settings were left untouched, and they can be removed when the rest of the legacy variables are removed. 
In particular, in our legacy infrastructure we managed our s3 encryption ourselves, including a key and roles that were assigned to the lambda function. In greenfield, this encryption is handled by default by AWS, so we can remove a lot of our custom configuration.
Related PR which added the bucket to greenfield: …
> BCDA-9143: Update aco creds bucket name for GF

- terraform/services/bucket-access-logs/main.tf
https://jira.cms.gov/browse/PLT-1107
Switched encryption for bucket to AES256.
With encryption set to KMS, the key used for server access logs in the bucket (arn:aws:kms:us-east-1:858827067514:key/6deaa81f-b9df-49cd-9405-fda86975d6d3) is owned by the logging service. We cannot decrypt objects encrypted with this key. As noted in the alert box at https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html, AES-256 is the only default encryption supported.
See checks.
> PLT-1107 Switch encryption for bucket-access-logs bucket to AES256

- terraform/services/snyk-integration/main.tf
https://jira.cms.gov/browse/PLT-1130
The policy was updated to separate global actions required by Snyk (ecr:GetAuthorizationToken, ecr:DescribeRepositories) from scoped repository actions, which are now restricted to only teams e.g bcda-*, dpc-*, ab2d-* ECR repositories.
This change ensures each team (e.g., BCDA, AB2D, DPC) can only scan their own ECR repositories in Snyk by restricting repository-level permissions in IAM policies. While Snyk requires global access to list all repositories (ecr:DescribeRepositories), teams can only add and scan images from their respective repos.
See checks.
link to successful tf plan https://github.com/CMSgov/ab2d-bcda-dpc-platform/actions/runs/15692016486/job/44209308692?pr=253.
please note plan fails for legacy account because snyk external id's was …
> PLT-1130:Create Roles and Policies for each API

- terraform/services/api-rds/main.tf
https://jira.cms.gov/browse/PLT-1152
Changes the ternary conditional to enable multi-AZ deployments for only production RDS instances.
As per the infrastructure meeting on 6/18: We're fine to keep multi-AZ RDS deployments in the production environments and remove them from sandbox.
> PLT-1152: Ensure DPC sandbox RDS deployment is single-az

- scripts/delete_secrets.sh
https://jira.cms.gov/browse/PLT-1214
Added a script to delete all AWS Secrets Manager secrets containing ab2d, bcda, or dpc in the name.
Includes support for a --dry-run mode to safely preview deletions.
We are transitioning our secret management approach to standardized SOPs using SSM Parameter Store instead of AWS Secrets Manager. As part of this transition, we are cleaning up legacy secrets that are no longer used. This script facilitates that cleanup in a safe and controlled way.
Tested locally using the --dry-run flag to confirm which secrets would be deleted.
> PLT-1214 script to delete secrets from secrets manager

- .github/workflows/tf-api-rds.yml
https://jira.cms.gov/browse/PLT-1237
BCDA is being removed from the tf-api-rds Github actions matrix in the CDAP repo.
As part of the migration to Aurora in all four BCDA environments, no related resources should continue to be managed by the legacy shared RDS Terraform in order to prevent unintended consequences (such as here (https://github.com/CMSgov/cdap/actions/runs/16354685093/job/46210040071#:~:text=test.cx2o6o4o45ut.us%2D-,east,-%2D1.rds.amazonaws) where the test and dev DNS records were reverted to point back to RDS from Aurora).
The following plan shows that only the four DPC jobs are left in the matrix: https://github.com/CMSgov/cdap/actions/runs/16605597386
> [PLT-1237] Removing BCDA from GHA RDS matrix.

- terraform/modules/aurora/README.md
- terraform/modules/aurora/main.tf
- terraform/modules/aurora/variables.tf
https://jira.cms.gov/browse/PLT-1236
- Adds variables to handle overrides on the default naming for security and subnet groups.
- Enables IAM auth by default.
- Enables copying tags from cluster instances to snapshots by default.
- Disables final snapshots.
As part of the DPC migration from RDS to Aurora clusters, we needed to override the naming enforced by the aurora module by default on some resources. We also have a security ask to enable IAM authentication, so this will enable that by default moving forward.
* dpc-test Aurora instance was deployed with this version of the module
* this is functional across ab2d `dev`, `test`, `sandbox`, and `prod`
> PLT-1236: Add overrides for security groups and subnet groups, enable IAM auth by default, disable final snapshots, and copy tags to snapshots

- terraform/modules/aurora/main.tf
https://jira.cms.gov/browse/PLT-1208
This PR adds a lifecycle block to the aws_security_group.this resource in the Aurora module that will cause Terraform to ignore changes to the security group description.
This change is required to prevent Terraform from destroying and then recreating a security group where the description does not match the one generated by the Aurora module since security group metadata (such as name and description) cannot be edited.
A security_group_name override has already been implemented to work around importing a security group with a different name, but rather than adding another workaround for the description is seems more straightforward to just ignore the description on imported resources.
This change was validated on the BCDA test environment by importing …
> [PLT-1208] Ignore SG description change in Aurora module

- terraform/services/admin-aco-deny/main.tf
- terraform/services/admin-create-aco-creds/main.tf
- terraform/services/admin-create-aco/main.tf
- terraform/services/admin-create-group/main.tf
- terraform/services/api-waf-sync/main.tf
https://jira.cms.gov/browse/PLT-1269
Add bcda config kms key to bcda services to read the values in param store.
We updated our functions to use the shared kms keys but for bcda we need to add the config kms key to more services to read values stored in param store.
See checks.
> PLT-1269 Add BCDA config kms key to more services

- terraform/modules/aurora/main.tf
https://jira.cms.gov/browse/PLT-1208
This PR adds a Terraform lifecycle ignore rule for the Aurora module instance parameter group description.
The BCDA sandbox and prod instance parameter groups have descriptions that slightly differ from what the Aurora module is expecting. Since the description field on instance parameter groups is immutable, this change is required in order to prevent Terraform from attempting to replace the parameter groups after the pre-existing groups have been imported into the sandbox and prod states.
This change was validated by importing pre-existing Aurora resources into the sandbox and prod environments and then verifying that subsequent `terraform plan` did not include replacing the parameter groups.
> PLT-1208: Add lifecycle ignore rule to Aurora instance parameter group.

- terraform/modules/aurora/variables.tf
https://jira.cms.gov/browse/PLT-1320
The default value for the aws_backup_tag in the Aurora module was updated to the current version.
The aws_backup_tag changed and required an update in the Aurora module.
This is a trivial default value update.
> [PLT-1320] Update aws_backup_tag default in Aurora module

- terraform/modules/cluster/main.tf
https://jira.cms.gov/browse/PLT-1328
This prefers the `target_key_arn` over the `target_key_id` in the cluster module's storage configuration. Without this, usage of this module produces unnecessary/meaningless diffs on every apply.
Post-greenfield migration tasks and standardization for ECS and Fargate.
As implemented, this was successfully applied against AB2D's `dev` infrastructure and **will** successfully apply to similar environments.
> PLT-1328: Use target_key_arn for cluster storage

- .github/workflows/tf-admin-aco-deny.yml
- .github/workflows/tf-admin-create-aco-creds.yml
- .github/workflows/tf-admin-create-aco.yml
- .github/workflows/tf-admin-create-group.yml
- .github/workflows/tf-alarm-to-slack.yml
- .github/workflows/tf-api-waf-sync.yml
- .github/workflows/tf-api-waf.yml
- .github/workflows/tf-backup-plan.yml
- .github/workflows/tf-bucket-access-logs.yml
- .github/workflows/tf-cclf-import.yml
- .github/workflows/tf-external-services-ip-sets.yml
- .github/workflows/tf-github-actions-oidc-provider.yml
- .github/workflows/tf-github-actions-role.yml
- .github/workflows/tf-kms-keys.yml
- .github/workflows/tf-opt-out-export.yml
- .github/workflows/tf-opt-out-import.yml
- .github/workflows/tf-security-groups.yml
- .github/workflows/tf-snyk-integration.yml
- .github/workflows/tf-tfstate.yml
https://jira.cms.gov/browse/PLT-1332
This PR adds a cron trigger of '12 14 * * 1-5' to all TF service workflows to ensure that they are run at 9:12am or 10:12am (depending on daylight savings) every weekday.
This change is being made to ensure that Terraform drift in any CDAP service will be caught and corrected within one business day.
When these changes were pushed to a remote branch the 'on push' trigger ran all affected workflows successfully. While this did not exercise the cron triggers directly, it shows that the workflows remain syntactically correct with the addition of the cron triggers.
> [PLT-1332] Adding cron trigger to service workflows.

- terraform/modules/aurora/main.tf
https://jira.cms.gov/browse/PLT-1342
default force_ssl cluster parameter has been added in aurora module
need to standardize default force_ssl cluster parameter across all apis, with shared aurora module in place. its best to have this in module and api teams consume module rather than have it set in apis infra directly.
The Terraform plan for the Aurora module changes has been validated in [BCDA-OPS PR #1268](https://github.com/CMSgov/bcda-ops/pull/1268).
> PLT-1342: Set default force_ssl cluster parameter in aurora module

- terraform/modules/service/main.tf
https://jira.cms.gov/browse/BCDA-9395
Updated the name of the ecs service execution role to include the full service name (including app and env) to avoid name clashes between different apps and envs.
> BCDA-9395: use full service name for execution role
